# dataset setting
inter_path : './dataset/Baby_Modern_SigLIP_Large/baby_modern.inter'
text_feat_path : './dataset/Baby_Modern_SigLIP_Large/text_feat.pt'
image_feat_path : './dataset/Baby_Modern_SigLIP_Large/image_feat.pt'

num_epochs : 500
eval_every : 1
test_every : 5
num_workers : 4
max_no_improvement : 10

num_users : 19357
num_items : 7015

max_seq_len : 50

attn_embed_dim : 256
text_dim : 1024
visual_dim : 1024
hidden_size : 256

lr_factor : 0.1

train_batch_size : 1024
test_batch_size : 512

attn_layers : 4

weight_decay : 0.01
top_k : 50

dropout : 0.1
attn_heads : 8
emb_dropout : 0.3
